// Created by dkargin on 2/25/25.
//

#include "miniros/console.h"
#include "miniros/rosassert.h"

#include "miniros/transport/advertise_service_options.h"

namespace miniros {

void AdvertiseServiceOptions::reportMismatchServiceMd5(const char* serviceName)
{
  MINIROS_FATAL("the request and response parameters to the server "
  "callback function must be autogenerated from the same "
  "server definition file (.srv). your advertise_servce "
  "call for %s appeared to use request/response types "
  "from different .srv files.", serviceName);
  MINIROS_BREAK();
}

} // namespace miniros
